# .github/workflows/flutter_tests.yml

name: Flutter Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  unit_tests:
    name: Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          channel: 'stable'
          cache: true

      - name: Instalar dependências
        run: flutter pub get

      - name: Rodar testes unitários
        run: flutter test test/test_metro_mockito.dart --reporter=expanded

      - name: Rodar testes existentes
        run: flutter test test/game_controller_test.dart test/guess_evaluator_test.dart --reporter=expanded